/**
 * Build script that:
 * 1. Scans the ../docs/ directory for Markdown files
 * 2. Reads frontmatter and content
 * 3. Generates a TypeScript file with all doc content
 * 4. Generates a search index JSON
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { glob } from 'glob';
import matter from 'gray-matter';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DOCS_DIR = path.resolve(__dirname, '../../docs');
const OUTPUT_DIR = path.resolve(__dirname, '../src/content');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'docs-content.ts');
const SEARCH_INDEX_FILE = path.join(OUTPUT_DIR, 'search-index.json');

interface DocEntry {
  title: string;
  description?: string;
  path: string;
  section: string;
  content: string;
}

interface SearchEntry {
  title: string;
  path: string;
  section: string;
  headings: string[];
}

// Normalize path from docs-relative path
function filePathToRoute(relativePath: string): string {
  const withoutExt = relativePath.replace(/\.md$/, '');
  if (withoutExt === 'overview') return '/docs/overview';
  if (withoutExt.startsWith('ui/')) return `/docs/${withoutExt}`;
  if (withoutExt.startsWith('dev/')) return `/docs/${withoutExt}`;
  if (withoutExt.startsWith('features/')) return `/docs/${withoutExt}`;
  if (withoutExt.startsWith('api/')) return `/docs/${withoutExt}`;
  // Root level docs files
  if (withoutExt === 'QUICK_START') return '/docs/QUICK_START';
  if (withoutExt === 'DEPLOYMENT') return '/docs/DEPLOYMENT';
  if (withoutExt === 'concepts') return '/docs/concepts';
  if (withoutExt === 'workflows') return '/docs/workflows';
  return `/docs/${withoutExt}`;
}

// Determine section from docs-relative path
function getSection(relativePath: string): string {
  if (relativePath.startsWith('ui/')) return 'Using WeRSS';
  if (relativePath.startsWith('dev/')) return 'Developer Docs';
  if (relativePath.startsWith('features/')) return 'Features';
  if (relativePath.startsWith('api/')) return 'API Reference';
  if (['overview.md', 'concepts.md', 'workflows.md'].includes(path.basename(relativePath))) return 'Core Concepts';
  return 'Get Started';
}

// Extract headings for search index
function extractHeadings(content: string): string[] {
  const headings: string[] = [];
  const regex = /^#{1,3}\s+(.+)$/gm;
  let match;
  while ((match = regex.exec(content)) !== null) {
    headings.push(match[1].trim());
  }
  return headings;
}

async function build() {
  console.log('🔍 Scanning docs directory...');

  // Find all markdown files, excluding specific files
  const files = await glob('**/*.md', { cwd: DOCS_DIR, ignore: ['**/node_modules/**', '**/DOCS_SITE_PLAN_FOR_GLM.md', '**/DOCUMENTATION_*.md'] });

  const docsContent: Record<string, string> = {};
  const searchEntries: SearchEntry[] = [];

  for (const file of files) {
    const filePath = path.join(DOCS_DIR, file);
    const content = fs.readFileSync(filePath, 'utf-8');
    const { data: frontmatter, content: markdown } = matter(content);

    const route = filePathToRoute(file);
    const section = getSection(file);
    const title = frontmatter.title || frontmatter.name || path.basename(file, '.md');
    const headings = extractHeadings(markdown);

    // Normalize route key for the app
    const routeKey = route.replace(/^\//, '');
    docsContent[routeKey] = markdown;

    searchEntries.push({
      title,
      path: route,
      section,
      headings,
    });

    console.log(`  ✅ ${route} (${section})`);
  }

  // Generate docs-content.ts
  console.log('\n📦 Generating content bundle...');
  const contentLines = [
    '// Auto-generated by scripts/build-docs.ts',
    '// Do not edit manually',
    '',
    'export const docsContent: Record<string, string> = {',
  ];

  for (const [key, content] of Object.entries(docsContent)) {
    const escaped = content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\${/g, '\\${');
    contentLines.push(`  ${JSON.stringify(key)}: \`${escaped}\`,`);
  }

  contentLines.push('};');
  contentLines.push('');
  contentLines.push('// Inject into window for static build');
  contentLines.push('if (typeof window !== "undefined") {');
  contentLines.push('  (window as any).__DOCS_CONTENT__ = docsContent;');
  contentLines.push('}');

  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, contentLines.join('\n'));
  console.log(`  Written: ${OUTPUT_FILE}`);

  // Generate search index
  fs.writeFileSync(SEARCH_INDEX_FILE, JSON.stringify(searchEntries, null, 2));
  console.log(`  Written: ${SEARCH_INDEX_FILE}`);

  console.log('\n✅ Build complete!');
  console.log(`   Documents: ${files.length}`);
  console.log(`   Search entries: ${searchEntries.length}`);
}

build().catch((err) => {
  console.error('❌ Build failed:', err);
  process.exit(1);
});
